SERVER_PORT: "8080"
SMS_PLATFORM_URL: "http://172.16.99.6/csp/hsb/DHC.Published.PUB0010.BS.PUB0010.cls"
SOAP_ACTION: "http://www.dhcc.com.cn/DHC.Published.PUB0010.BS.PUB0010.HIPMessageServer"
PHONE_NUMBERS: [ "15838199504", "13951073551" ]
SMS_SEND_INTERVAL: "2"
SEND_REAL_SMS: false

# 添加数据库配置信息
DB:
  HOST: "172.16.97.109"
  USER: "dolphin"
  PASSWORD: "dolphin"
  DATABASE: "dolphinscheduler2"
